repositories:
  - name: acr
    url: acr200.azurecr.io
    oci: true
releases:
  - name: hello2
    chart: acr/hello-world
    version: 2.0.0
    values:
      - values-{{ .Environment.Name }}.yml
environments:
  entwicklung: {}
  abnahme: {}
  produktion: {}